# -*- coding: utf-8 -*-
"""app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Jlvtwqpb-lQGvuFr72Q_Sh6k8kCYrJ6
"""

!pip install flask-ngrok
!pip install transformers

from transformers import GPT2LMHeadModel,GPT2Tokenizer
from flask import Flask,request,jsonify
from flask_ngrok import run_with_ngrok

tokenizer = GPT2Tokenizer.from_pretrained('gpt2-large')
model = GPT2LMHeadModel.from_pretrained("gpt2-large",pad_token_id=tokenizer.eos_token_id)

app = Flask(__name__)
run_with_ngrok(app)

@app.route("/",methods=['POST'])
def create():
  sen = request.form('topic')
  len = request.form('length')
  input_ids = tokenizer.encode(sen,return_tensors='pt')
  res = model.generate(input_ids,max_length=len,num_beams=5,no_repeat_ngram_size=2,early_stopping=True)
  ans= tokenizer.decode(res[0],skip_special_tokens=True)
  return jsonify({"response":ans}), 200

if __name__ == "__main__":
  app.run()

